# English Configuration Override

lang: en-US

title: ULALA-X Dev Notes
tagline: Game Servers & Server Communication
description: >-
  Development notes and experiences on game servers and server communication,
  featuring open source projects like playhouse and zeromq.

baseurl: "/en"
